### ISSUE TITLE
Folder structuur

### ISSUE THREAD

**Issue by BerendWeij** [BeauArthurs/myth#3]
``` c
    ..      
EnemyController.cs      
EnemyController.cs.meta 
```

Bestand: https://github.com/BeauArthurs/myth/blob/master/Assets/Scripts/EnemyController.cs

Groepeer je code volgens een duidelijke onderverdeling.
Bijvoorbeeld:

Debug/
Gameplay/
    Actors/
    Items/
Framework/
GUI/
...

Ook hierbinnen kun je nog specifieke folders aanmaken. Probeer te voorkomen dat je in een folder heel veel script bestanden hebt staan.

Vaak verdeel je het:
- of aan de hand van de verschillende objecten (enemy, turret, etc.)
- of aan de hand van de design pattern (dus factories in de map 'factories'). Later dit jaar gaan we naar andere design patterns kijken.

**Comment by RichardRam87** [comment]
Het is nu bijna drie weken later en dit is nog steeds niet in orde. Doe dit zsm zodat je project overzichtelijk blijft...
